import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center p-6 relative">
      <div className="absolute top-[10%] left-1/2 -translate-x-1/2 w-200 h-200 bg-primary/20 rounded-full blur-[120px] pointer-events-none"></div>
      {/* Unterer indigo-farbener Orb */}
      <div className="absolute bottom-[-10%] right-[-5%] w-150 h-150 bg-indigo-custom/10 rounded-full blur-[100px] pointer-events-none"></div>
      <div className="relative z-10 w-full max-w-95">
        <div className="flex flex-col items-center mb-8">
          <div className="size-20 bg-linear-to-br from-indigo-500/20 to-violet-500/20 rounded-2xl flex items-center justify-center border border-violet-500/30 mb-6 logo-glow">
            <span className="material-symbols-outlined text-white text-[52px] fill-1">
              bolt
            </span>
          </div>
          {children}
        </div>
      </div>
    </div>
  );
}
